services:
  postgres:
    image: postgres:16-alpine
    container_name: traveltracker_db
    restart: always
    env_file:
      - db.env           
    volumes:
      - db_data_postgres:/var/lib/postgresql/data
      # Mounting schema + csv + loader so they run on first init
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - travel

  app:
    build: .
    container_name: traveltracker_app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - app.env          
    networks:
      - travel

volumes:
  db_data_postgres:

networks:
  travel:
